package io.mycat;

public enum MycatDataContextEnum {
    DEFAULT_SCHEMA,
    IS_MULTI_STATEMENT_SUPPORT,
    IS_LOCAL_IN_FILE_REQUEST_STATE,
    AFFECTED_ROWS,
    WARNING_COUNT,
    CHARSET_INDEX,
    IS_AUTOCOMMIT,
    ISOLATION,
    LAST_MESSAGE,
    LAST_INSERT_ID,
    SERVER_CAPABILITIES,
    LAST_ERROR_CODE,
    SQL_STATE,
    CHARSET_SET_RESULT,
    SELECT_LIMIT,
    NET_WRITE_TIMEOUT,
    IS_READ_ONLY,
    IS_IN_TRANSCATION,
    USER_INFO
    ,
    ;
}