package io.mycat.mysql;

public enum MySQLPayloadType {
    UNKNOWN, ERROR, OK, EOF, COLUMN_COUNT, CHARACTER_SET, PREPARE_OK, COULUMN_DEFINITION, TEXT_RESULTSET_ROW, BINARY_RESULTSET_ROW, LOCAL_INFILE_REQUEST
}
