package io.mycat.mycat2.cmds;

public enum LoadDataState {
    NOT_LOAD_DATA,
    CLIENT_2_SERVER_COM_QUERY,
    SERVER_2_CLIENT_COM_QUERY_RESPONSE,
    CLIENT_2_SERVER_CONTENT_FILENAME,
    CLIENT_2_SERVER_EMPTY_PACKET,
    SERVER_2_CLIENT_OK_PACKET;
}
