package io.mycat.proxy.packet;

public enum MySQLPayloadType {
    UNKNOWN,
    ERROR,
    OK,
    EOF,
    COLUMN_COUNT,
    CHARACTER_SET,
    PREPARE_OK,
    COLUMN_DEFINITION,
    TEXT_RESULTSET_ROW,
    BINARY_RESULTSET_ROW,
    LOCAL_INFILE_REQUEST,
    LOCAL_INFILE_CONTENT_OF_FILENAME,
    LOCAL_INFILE_EMPTY_PACKET,
    SEND_LONG_DATA,
    COM_STMT_CLOSE,
}
